### ISSUE TITLE
import error for holoviews

### ISSUE THREAD

**Issue by dchudz** [mrocklin/dask-tutorial#6]
This is in binder, having launched binder from the link in the README.

<img width="732" alt="Screen Shot 2022-11-08 at 11 46 29 AM" src="https://user-images.githubusercontent.com/1222726/200625376-62cfc2bf-89e5-49e1-9edd-76957ccfa455.png">

**Comment by ncclementi** [comment]
Yup, that's because holoviews is not in the binder env. Just opened a PR

**Comment by mrocklin** [comment]
Yeah, this notebook wasn't really camera ready.  It should be better now though.
